### ISSUE TITLE
Suggested modification to config_line_end filter plugin

### ISSUE THREAD

**Issue by th-geb** [O-X-L/ansible-role-nginx#2]
Hello,

should the code line 21 in filter_plugins/utils.py

(
https://github.com/ansibleguy/infra_nginx/blob/d8721d82c70227c8a6ac9f7b9345395732dc2af6/filter_plugins/utils.py#L19-L21
)

not be
return '' if line.endswith(';') or line.endswith('}') else ';'

but
return '' if line.endswith(';') or line.endswith('{') or line.endswith('}') else ';'
?

I ask because without this modification I get a syntax error in the nginx site config
when I apply

ansibleguy.sw_semaphore/defaults/main/1_main.yml

...
    config_additions:
      - 'chunked_transfer_encoding on;'
      - 'location /api/ws {'   <--------------
      - '  proxy_pass http://127.0.0.1:3000/api/ws;'
      - '  proxy_http_version 1.1;'
      - '  proxy_set_header Upgrade $http_upgrade;'
      - '  proxy_set_header Connection "upgrade";'
      - '  proxy_set_header Origin "";'
      - '}'

Thanks, Thomas

**Comment by ansibleguy** [comment]
Thank you for notifying me. You are right.
Would you mind testing the fix on latest?
`ansible-galaxy role install git+https://github.com/ansibleguy/infra_nginx`

**Comment by th-geb** [comment]
Hello ansibleguy,
thank you very much for the fix! Works fine for me!
Thanks, Thomas
